# -*- coding: utf-8 -*-

import os

import numpy as np
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
from scipy.ndimage.filters import gaussian_filter

from allensdk.brain_observatory.ecephys.ecephys_project_cache import EcephysProjectCache
from allensdk.brain_observatory.ecephys.ecephys_session import (
    EcephysSession, 
    removed_unused_stimulus_presentation_columns
)

# This code constructs the units data frame used for Figure 1, Figure 3,
# and Extended Data Figures 1, 4, and 10

### PATH VARIABLES ##############################
cache_directory = '/media/huklaban5/Data/MouseV2/' #'/mnt/nvme0/ecephys_cache_dir_2'
code_directory = '/home/huklaban5/Documents/MouseV2/Hierarchy_analysis/neuropixels_platform_paper/' #'/home/joshs/GitHub/neuropixels_platform_paper'
###################################################

# %%

# 1. Download pre-computed response metrics from AllenSDK

manifest_path = os.path.join(cache_directory, "manifest.json")
cache = EcephysProjectCache.from_warehouse(manifest=manifest_path)

metrics = cache.get_unit_analysis_metrics_by_session_type('brain_observatory_1.1', filter_by_validity=False, amplitude_cutoff_maximum = np.inf,
                                                          presence_ratio_minimum = -np.inf,
                                                          isi_violations_maximum = np.inf)

metrics2 = cache.get_unit_analysis_metrics_by_session_type('functional_connectivity', filter_by_validity=False, amplitude_cutoff_maximum = np.inf,
                                                          presence_ratio_minimum = -np.inf,
                                                          isi_violations_maximum = np.inf)

all_metrics = pd.concat([metrics, metrics2], sort=True)

# %% 

# 2. Add time to first spike (not included in data release)

first_spike = pd.read_csv(os.path.join(code_directory, 'data', 'time_to_first_spike.csv'),index_col=0)

all_metrics = all_metrics.merge(first_spike, on='ecephys_unit_id', sort=False)

# %%

# 3. Add layer info and cortical depth (derived from CCF annotations)

layer_info = pd.read_csv(os.path.join(code_directory, 'data', 'layer_info.csv'),index_col=0)

all_metrics = all_metrics.merge(layer_info, on='ecephys_unit_id', sort=False)

# %%

# 4. Add intrinsic timescale and response decay timescale

timescale_metrics = pd.read_csv(os.path.join(code_directory, 'data', 'timescale_metrics.csv'),
                                             index_col=0, low_memory=False)

all_metrics = all_metrics.merge(timescale_metrics, on='ecephys_unit_id', how='outer')

# %%

# 5. Append new V1-site metrics generated by generate_retinotopic_csvs.py
new_sites = ['site2', 'site3', 'site4', 'site5']
for site in new_sites:
    data_dir = os.path.join(code_directory, 'data', f'{site}_processed')
    if not os.path.isdir(data_dir):
        print(f'Warning: missing {data_dir}; skipping {site}')
        continue

    # Load per-site metrics
    mod_path = os.path.join(data_dir, 'change_modulation_data.csv')
    tau_path = os.path.join(data_dir, 'timescale_metrics.csv')
    layer_path = os.path.join(data_dir, 'layer_info.csv')
    ttf_path = os.path.join(data_dir, 'time_to_first_spike.csv')

    def safe_read(path):
        return pd.read_csv(path) if os.path.isfile(path) else pd.DataFrame()

    mod = safe_read(mod_path)
    tau = safe_read(tau_path)
    layer = safe_read(layer_path)
    ttf = safe_read(ttf_path)

    # Harmonize column names to match Figure3 expectations
    if 'modulation_index' in mod.columns:
        mod = mod.rename(columns={'modulation_index': 'mod_idx_dg'})
    if 'autocorr_tau' in tau.columns:
        tau = tau.rename(columns={'autocorr_tau': 'timescale_ac'})
    if 'time_to_first_spike' in ttf.columns:
        ttf = ttf.rename(columns={'time_to_first_spike': 'time_to_first_spike_fl'})

    # Align key to SDK schema: ecephys_unit_id
    for df2 in (mod, tau, layer, ttf):
        if 'unit_id' in df2.columns:
            df2.rename(columns={'unit_id': 'ecephys_unit_id'}, inplace=True)

    # Merge per-site tables on ecephys_unit_id
    site_df = layer
    if not mod.empty:
        site_df = site_df.merge(mod, on='ecephys_unit_id', how='outer')
    if not tau.empty:
        site_df = site_df.merge(tau, on='ecephys_unit_id', how='outer')
    if not ttf.empty:
        site_df = site_df.merge(ttf, on='ecephys_unit_id', how='outer')

    # Append into all_metrics
    if not site_df.empty:
        all_metrics = pd.concat([all_metrics, site_df], ignore_index=True, sort=True)

# 6. Write to a CSV file for use by other scripts

out_path = os.path.join(code_directory, 'data', 'unit_table.csv')
all_metrics.to_csv(out_path)
print(f'Wrote {out_path}, rows={len(all_metrics)}')
