"""Manuscript legend generated from the same inputs and estimates as Figure 4.

Edit panel descriptions here when changing methods; numerical counts, row order,
interval conclusions, and the result table are derived at render time.
"""
from scripts import build_figure4_variant_review as figure


def generate_legend(*, entries, displayed_entries, records, identity, n_draws, seed,
                    timescale_limits, fov_count=12):
    n_animals = displayed_entries.subject_id.nunique()
    n_probes = displayed_entries.probe.nunique()
    n_entries = len(displayed_entries)
    n_border = int((~displayed_entries.surface_agrees_visp.astype(bool)).sum())
    n_omitted = len(set(entries.subject_id) - set(displayed_entries.subject_id))
    omitted_note = (
        f" {n_omitted} additional animal{'s are' if n_omitted != 1 else ' is'} omitted from this anatomical "
        "panel pending resolution of probe-track assignments but retained in the functional analyses."
        if n_omitted else ""
    )
    location_names = ', '.join(figure.PROBE_DISPLAY_LABELS[p].lower() for p in figure.PROBE_ORDER)
    area_names = ', '.join(figure.AREA_ORDER)
    rows = '; '.join(label.replace('\n', ' ').replace('†', '')
                     for label, _, _ in figure.LOCATION_EFFECT_ROWS)
    control = {r['metric']: r for r in records if r['comparison'] == 'control'}
    pair_counts = ', '.join(str(control[m]['n_sessions']) for m in figure.METRICS)
    within_counts = ', '.join(str(next(r['n_sessions'] for r in records
                                     if r['metric'] == m and r['comparison'] == 'v1'))
                              for m in figure.METRICS)
    included = [short for metric, short in zip(figure.METRICS, figure.SHORT_METRICS)
                if identity[metric]['delta_low'] <= 0 <= identity[metric]['delta_high']]
    if len(included) == len(figure.METRICS):
        interval_statement = 'All three difference intervals include zero, leaving the relative magnitudes unresolved.'
    elif included:
        interval_statement = ('Difference intervals include zero for ' + ', '.join(included) +
                              '; the remaining difference intervals exclude zero.')
    else:
        interval_statement = 'All three difference intervals exclude zero.'
    lo, hi = timescale_limits
    text = f'''<!-- Generated by scripts/build_figure4_location_controls.py; edit scripts/figure4_location_controls_legend.py, not this file. -->

**Figure 4. Large-scale OpenScope recordings provide a within-area benchmark for functional heterogeneity.**

**A)** Locations of {n_probes} V1 recording sites in the MouseV2 OpenScope dataset, displayed on the dorsal Allen CCFv3 atlas. Large outlined circles indicate arithmetic mean anterior–posterior and medial–lateral coordinates across {n_animals} animals; smaller points show individual penetrations. Colors identify {location_names} sampling locations. Positions represent the most superficial electrode assigned to V1 on each probe. All {n_entries} positions contribute to the means, including {n_border} outside the atlas’s dorsal V1 outline. This is an average layout across animals.{omitted_note}

**B)** Schematic of {fov_count} two-photon imaging fields of view in a single mouse, overlaid on a widefield retinotopic map. Colors distinguish imaging locations for visualization and do not indicate anatomical groups.

**C–D)** Session-level time to first spike (TTFS), phase modulation (log10 F1/F0), and neuronal response timescale across {len(figure.PROBE_ORDER)} V1 sampling locations in MouseV2 (**C**) and {len(figure.AREA_ORDER)} higher visual areas—{area_names}—in the Allen Brain Observatory Neuropixels dataset (**D**). Points represent session means; shaded half-violins show their distributions, and colored bars and whiskers indicate means and normal-approximation 95% confidence intervals. Locations are treated categorically. MouseV2 analyses include only neurons whose extremum electrode is assigned to V1; session-by-location groups with fewer than {figure.MIN_V1_UNITS} eligible neurons are excluded.

**E)** Variation associated with recording location. Colored circles show bias-corrected explained variance (ω²), expressed as a percentage. From top to bottom, rows show: {rows}. The Within V1 and Across HVAs rows quantify location effects; the Across HVAs vs within V1 row shows their difference (HVA minus V1), expressed in percentage points. The positive control (**†**) uses matched Allen sessions, pairing each session’s V1 mean with the equally weighted mean of its available HVA means ({pair_counts} session pairs for TTFS, F1/F0, and timescale, respectively). Its variance denominator differs from those of the location comparisons.

Colored whiskers indicate 95% percentile intervals from {n_draws:,} whole-session bootstrap replicates. Open gray squares and gray whiskers indicate the median and central 95% range of {n_draws:,} within-session label shuffles. The control shuffles V1/HVA labels within pairs; location comparisons shuffle available location labels within each session. Single-location sessions cannot change under this shuffle. The effect-difference row shows the difference between independently shuffled HVA and V1 estimates.

For the V1 group vs HVA group, Within V1, and Across HVAs rows, significance labels denote uncorrected, one-sided shuffle tests: \\* *p* < .05, \\*\\* *p* < .01, \\*\\*\\* *p* < .001; n.s., *p* ≥ .05. For the effect-difference row, n.s. (**‡**), when present, indicates that the bootstrap interval includes zero; this is not a shuffle-test result. {interval_statement} Negative explained-variance estimates are retained as a consequence of bias correction.

**F–G)** Single-neuron response-timescale distributions across V1 locations (**F**) and HVAs (**G**). Kernel-density distributions give equal weight to each session and to each neuron within a session; repeated estimates from a neuron share its weight. Vertical lines indicate weighted medians, and annotations report unique-neuron and session counts. The displayed range is {lo:g}–{hi:g} ms. MouseV2 neurons satisfy the same anatomical V1 restriction used in C–E.

---

Generated analysis details (supporting information, separate from the manuscript legend):

Within-V1 session counts for TTFS, F1/F0, and timescale: {within_counts}.
Bootstrap/shuffle draws: {n_draws:,}; initial bootstrap seed: {seed}; control/bootstrap/shuffle stream seed: {seed + 1}.

| Metric | Comparison | Explained variance (%) | 95% bootstrap interval (%) | One-sided shuffle p |
|---|---|---:|---:|---:|
'''
    row_names = {key: label.replace('\n', ' ').replace('†', '')
                 for label, key, _ in figure.LOCATION_EFFECT_ROWS}
    indexed = {(r['metric'], r['comparison']): r for r in records}
    for metric in figure.METRICS:
        for _, key, _ in figure.LOCATION_EFFECT_ROWS:
            if key == 'delta':
                stats = identity[metric]
                text += (f"| {metric} | {row_names[key]} (percentage points) | {100*stats['delta']:.2f} | "
                         f"{100*stats['delta_low']:.2f} to {100*stats['delta_high']:.2f} | Not tested |\n")
            else:
                r = indexed[metric, key]
                text += (f"| {metric} | {row_names[key]} | {100*r['observed']:.2f} | "
                         f"{100*r['bootstrap_low']:.2f} to {100*r['bootstrap_high']:.2f} | "
                         f"{r['permutation_p_greater']:.6f} |\n")
    text += ('\nReproduce with `MPLBACKEND=Agg python scripts/build_figure4_location_controls.py`. '
             'Figure, legend, analysis inputs, statistics, and mean probe positions are saved together in `Figure3/`.\n')
    return text
